export enum ROUTE_NAME {
  ADMIN_HOME = 'ADMIN.HOME',
  ADMIN_USERS = 'ADMIN.USERS',
  ADMIN_AGENTS = 'ADMIN.AGENTS',
  ADMIN_AGENT_GROUP = 'ADMIN.AGENT.GROUP',
  // Deliver
  DELIVER_HOME = 'DELIVER.HOME',
  LOGIN = 'AUTH.LOGIN',
}
