export enum ROUTE_NAME {
  ADMIN_HOME = 'ADMIN.HOME',
  ADMIN_USERS = 'ADMIN.USERS',
  ADMIN_PERSONAL_GROUP = 'ADMIN.PERSONAL.GROUP',
  // Deliver
  DELIVER_HOME = 'DELIVER.HOME',
  LOGIN = 'AUTH.LOGIN',
}
