export enum ROUTE_NAME {
  // Admin || Manager
  ADMIN_HOME = 'ADMIN.HOME',
  ADMIN_USERS = 'ADMIN.USERS',
  ADMIN_AGENTS = 'ADMIN.AGENTS',
  ADMIN_AGENT_GROUP = 'ADMIN.AGENT.GROUP',
  ADMIN_AGENTS_MAP = 'ADMIN.AGENT.MAP',
  ADMIN_ASSIGNMENT = 'ADMIN.ASSIGNMENT',
  ADMIN_ASSIGNMENTS = 'ADMIN.ASSIGNMENTS',
  ADMIN_EVENTS = 'ADMIN.EVENTS',
  ADMIN_CLIENTS = 'ADMIN.CLIENTS',
  // Agent
  AGENT_ASSIGNMENT = 'AGENT.ASSIGNMENT',
  AGENT_ASSIGNMENTS = 'AGENT.ASSIGNMENTS',
  AGENT_CHECKPOINT = 'AGENT.CHECKPOINT',
  AGENT_HOME = 'AGENT.HOME',
  AGENT_REPORTS = 'AGENT.REPORTS',
  AGENT_PROFILE = 'AGENT.PROFILE',
  LOGIN = 'AUTH.LOGIN',
}
