### Create
POST /api/agents HTTP/1.1
Host: {{ host }}
Authorization: {{token}}

{
    "address": "Agent Address",
    "others": "Others",
    "nick": "AgentUserName",
    "categories": [1],
    "position": {
        "lat":0,
        "lng":0
    },
    "user_id": 3,
    "agent_group_id": 1
}

### FIND
GET /api/agents/1 HTTP/1.1
Host: {{ host }}
Authorization: {{token}}

### LIST
GET /api/agents HTTP/1.1
Host: {{ host }}
Authorization: {{token}}

### Remove
DELETE /api/agents/1 HTTP/1.1
Host: {{ host }}
Authorization: {{token}}

### Update
PATCH /api/agents/1 HTTP/1.1
Host: {{ host }}
Authorization: {{token}}

{
    "address": "Agent Address",
    "others": "Others",
    "nick": "AgentUserName",
    "categories": [1],
    "position": {
        "lat":0,
        "lng":0
    },
    "agent_group_id": 1,
    "bussy": true
}

### WHOAMI
GET /api/agents/whoami HTTP/1.1
Host: {{ host }}
Authorization: {{token}}
