### Create
POST /api/agents HTTP/1.1
Host: {{ host }}
Authorization: {{token}}

{
    "name": "agentName",
    "email": "a@email.com",
    "phone": "55887799",
    "address": "Agent Address",
    "others": "Others",
    "user_name": "AgentUserName",
    "password": "AgentPassword",
    "categories": [3,2],
    "coordinate": {
        "lat":0,
        "lng":0
    }
}

### FIND
GET /api/agents/1 HTTP/1.1
Host: {{ host }}
Authorization: {{token}}

### Remove
DELETE /api/agents/1 HTTP/1.1
Host: {{ host }}
Authorization: {{token}}

### Update
PATCH /api/agents/1 HTTP/1.1
Host: {{ host }}
Authorization: {{token}}

{
    "name": "agentName",
    "phone": "55887799",
    "address": "Agent Address",
    "others": "Others",
    "user_name": "AgentUserName",
    "password": "AgentPassword",
    "categories": [3,2],
    "coordinate": {
        "lat":0,
        "lng":0
    }
}
