### Create
POST /api/assignments HTTP/1.1
Host: {{ host }}
Authorization: {{token}}

{
    "name": "agentName",
    "description": "AssignmentDescription",
    "observations": "Assignment observations",
    "event": "Assignment evebt",
    "state": "Assignment state",
    "joins":[
        {
            "checkpoint": "checkpoint",
            "status": "waiting",
            "initiated_ts": "2020-05-13"
        }
    ]
}

### FIND
GET /api/assignments/1 HTTP/1.1
Host: {{ host }}
Authorization: {{token}}

### Remove
DELETE /api/assignments/1 HTTP/1.1
Host: {{ host }}
Authorization: {{token}}

### Update
PATCH /api/assignments/1 HTTP/1.1
Host: {{ host }}
Authorization: {{token}}

{
    "name": "agentName",
    "description": "AssignmentDescription",
    "observations": "Assignment observations",
    "event": "Assignment evebt",
    "state": "Assignment state",
    "agent_id": 2
}
