#### Assignments List
GET /api/assignments
Authorization: {{token}}
Host: {{host}}

#### Assignments Create
POST /api/assignments
Authorization: {{token}}
Host: {{host}}

{
    "name": "agentName",
    "description": "AssignmentDescription",
    "observations": "Assignment observations",
    "event": "Assignment event",
    "checkpoints":[
        {
            "name": "CheckpointName",
            "position":{
                "lat":0,
                "lng":0
            },
            "contact": "55555555"
        }
    ]
}

#### Assignments FIND
GET /api/assignments/{assignment_id}
Authorization: {{token}}
Host: {{host}}

#### Assignments Remove
DELETE /api/assignments/{assignment_id}
Authorization: {{token}}
Host: {{host}}

#### Assignments Update
PATCH /api/assignments/{assignment_id}
Authorization: {{token}}
Host: {{host}}

{
    "name": "Assignment Checkpoint Update",
    "description": "AssignmentDescription Update",
    "observations": "Assignment observations Update",
    "event": "Assignment evebt Update",
    "status": 2,
    "agent_id": 1
}

#### Assignments Assign Checkpoint
POST /api/assignments/{assignment_id}/assign-checkpoint
Authorization: {{token}}
Host: {{host}}

{
    "name": "Assign Chekpoint",
    "position":{
        "lat":0,
        "lng":0
    },
    "contact": "55445566"
}

#### Assignment Search
POST /api/assignments/search
Authorization: {{token}}
Host: {{host}}

{
    "name": "Assignment Checkpoint Update",
    "description": "AssignmentDescription Update",
    "observations": "Assignment observations Update",
    "event": "Assignment evebt Update",
    "status": 2,
    "agent_id": 1
}

#### Update Checkpoint
PATCH /api/assignments/checkpoints/{checkpoint_id}
Authorization: {{token}}
Host: {{host}}

{
    "name": "Checkpoint Update",
    "position":{
        "lat":0,
        "lng":0
    },
    "contact": "55445566",
    "status": 2
}
