### Create
POST /api/users HTTP/1.1
Host: {{ host }}
Authorization: {{token}}

{
    "name": "userName",
    "email": "admin@admin.com",
    "phone": "55115511",
    "password": "admin",
    "password_confirmation": "admin"
}

### list users
GET /api/users/list HTTP/1.1
Host: {{ host }}
Authorization: {{token}}

### Auth Login
POST /api/users/login HTTP/1.1
Host: {{ host }}

{
    "email": "admin@godjango.dev",
    "password": "admin@godjango.dev"
}

### Get
GET /api/users HTTP/1.1
Host: {{ host }}
Authorization: {{token}}


### Update password
PATCH /api/users/2 HTTP/1.1
Host: {{ host }}
Authorization: {{token}}

{
    "current_password": "admin",
    "password": "password",
    "password_confirmation": "password"
}
